## Setup NFS Server ##
#
# Install NFS Client on All the Nodes ##
#

# Clone git repo #

git clone https://exxsyseng@bitbucket.org/exxsyseng/nfs-provisioning.git
cd nfs-provisioning

# RBAC # 

kubectl create -f rbac.yaml

# Create Storage Class #

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
        name: managed-nfs-storage
provisioner: example.com/nfs
        parameters:
                archiveOnDelete: "false"

kubectl get storageclass

# Deploy NFS Provisioner #

kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-client-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: example.com/nfs
            - name: NFS_SERVER
              value: 172.42.42.100
            - name: NFS_PATH
              value: /srv/nfs/kubedata
      volumes:
        - name: nfs-client-root
          nfs:
            server: 172.42.42.100
            path: /srv/nfs/kubedat
 
# Create Claims #
#
# Refer - https://blog.exxactcorp.com/deploying-dynamic-nfs-provisioning-in-kubernetes/
