---
apiVersion: v1
kind: PersistentVolume
metadata:
        name: myapp-pv
spec:
        storageClassName: mypv
        capacity:
                storage: 1Gi
        accessModes:
                - ReadWriteMany
        hostPath:
                path: "/mnt/pod-data"
...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: myapp-pvc
spec:
        persistentVolumeReclaimPolicy: Retain #Keep the Data|2. Delete - when PVC is deleted the PV is deleted | 3. Recycle - Deprecated 
        storageClassName: mypv
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 100M
...
