apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
      - name: job-app
        image: ubuntu
        command: ["echo", "Hello!"]
      restartPolicy: Never
