apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: prod
  ports:
    - protocol: TCP
      port: 80 # port on which service will listen
      targetPort: 9376 # port on which pod is listening
