apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
      initContainers:
      - name: init-app
        image: ubuntu
        command: ["/bin/bash"]
        args: ["-c", "echo '<h1>My App</h1>' > /app-data/index.html"]
        volumeMounts:
        - mountPath: /app-data
          name: msg
      containers:
      - name: webapp
        image: nginx
        ports:
                - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: msg
      volumes:
      - name: msg
        hostPath:
                path: /mnt/data/
                type: DirectoryOrCreate

