apiVersion: v1
kind: Pod
metadata:
        name: myfirstpod
spec:
        restartPolicy: Always #| Never | OnFailure
        containers:
                - name: myapp
                  image: alpine
                  imagePullPolicy: Always #| IfNotPresent | Never 
                  env:
                        - name: msg
                          value: "web server"
                  ports:
                        - containerPort: 80
                        - containerPort: 443

## Image Pull Policy ##
# 
# Always = Always pull the image.
#
# IfNotPresent = Only pull the image if it does not already exist on the node.
#
# Never = Never pull the image.
#
## Pod Restart Policy ##
#
# Always means that the container will be restarted even if it exited with a zero exit code (i.e. successfully). This is useful when you don't care why the container exited, you just want to make sure that it is always running (e.g. a web server). This is the default.
#
# OnFailure means that the container will only be restarted if it exited with a non-zero exit code (i.e. something went wrong). This is useful when you want accomplish a certain task with the pod, and ensure that it completes successfully - if it doesn't it will be restarted until it does.
#
# Never means that the container will not be restarted regardless of why it exited.
#
################
