apiVersion: v1
kind: Pod
metadata: 
        name: myfirstpod
spec:
        containers:
                - name: myapp
                  stdin: true
                  tty: true
                  image: ubuntu
