---
apiVersion: v1
kind: Pod
metadata:
        name: mypod
spec:
 restartPolicy: OnFailure
 containers:
  - name: myapp
    image: mysql
    imagePullPolicy: IfNotPresent
    env:
     - name: MYSQL_USER
       valueFrom:
        secretKeyRef:
         name: dbsecret
         key: dbuser
     - name: MYSQL_PASSWORD
       valueFrom:
        secretKeyRef:
         name: dbsecret
         key: dbpassword
     - name: MYSQL_ROOT_PASSWORD
       valueFrom:
        secretKeyRef:
         name: dbsecret
         key: dbrootpassword
     - name: MYSQL_DBNAME
       valueFrom:
        configMapKeyRef:
         name: dbconfig
         key: dbname
    volumeMounts:
     - name: myconfig
       mountPath: /etc/mysql/conf.d/
 volumes:
  - name: myconfig
    configMap:
     name: dbconfig
     items:
     - key: mysql
       path: my.cnf
