---
apiVersion: v1
kind: Pod
metadata:
        name: mypod
spec:
        containers:
                - name: mydb
                  image: mysql
                  env: 
                        - name: MYSQL_USER
                          valueFrom:
                                  secretKeyRef:
                                          name: mysecret 
                                          key: dbusername
                        - name: MYSQL_PASSWORD
                          valueFrom:
                                  secretKeyRef:
                                          name: mysecret
                                          key: dbpassword
                        - name: MYSQL_DATABASE
                          valueFrom:
                                  secretKeyRef:
                                          name: mysecret
                                          key: dbname
                        - name: MYSQL_ROOT_PASSWORD
                          valueFrom:
                                  secretKeyRef:
                                          name: mysecret
                                          key: dbRootPassword


