## Secrets
#
# Generate base64 encoded value
#
# echo -n 127.0.0.1 | base64
# echo -n wordpress | base64
# echo -n wpuser | base64
# echo -n redhat | base64
#
###

---
apiVersion: v1
kind: Secret
metadata:
        name: mysecret
type: Opaque
data:
        dbhost: <base64 encoded value>
        dbname: <base64 encoded value>
        dbusername: <base64 encoded value>
        dbpassword: <base64 encoded value>
        dbRootPassword: <base64 encoded value>
...

## Creating Secret through CLI
#
# kubectl create secret generic mysecret --from-literal=dbhost=127.0.0.1 --from-literal=dbname=wordpress --from-literal=dbname=wpuser --from-literal=dbpassword=redhat
