## Creating Secret ##
#
# ssh-keygen
# cd .ssh
# kubectl create secret ssh --from-file=authorized_keys=/root/.ssh/id_rsa.pub
#
##

---
apiVersion: v1
kind: Pod
metadata:
        name: mypod1
spec:
        containers:
                - name: mydb
                  image: ubuntu
                  stdin: true
                  tty: true
                  volumeMounts:
                        - name: myvol
                          mountPath: /etc/ssh-key
        volumes:
                - name: myvol
                  secret:
                          secretName: ssh

