## Horizontal Pod Autoscaler ## 
#
# The Horizontal Pod Autoscaler automatically scales the number of Pods in a replication controller, deployment, replica set or stateful set based on observed CPU utilization (or, with custom metrics support, on some other application-provided metrics). Note that Horizontal Pod Autoscaling does not apply to objects that can't be scaled, for example, DaemonSets.
#
#########
# Example:
#
# FROM php:5-apache
# COPY index.php /var/www/html/index.php
# RUN chmod a+rx index.php
#
########
# index.php
# <?php
#  $x = 0.0001;
#  for ($i = 0; $i <= 1000000; $i++) {
#    $x += sqrt($x);
#  }
#  echo "OK!";
# ?>
#
########
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  ports:
  - port: 80
  selector:
    run: php-apache

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mycpu-hpa
spec:
  mixReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  targetCPUUtilizationPercentage: 20


## Increase Load
# kubectl run -i --tty load-generator --rm --image=busybox --restart=Never -- /bin/sh -c "while sleep 0.01; do wget -q -O- http://php-apache; done"
#
# kubectl get hpa
#
# Docs Examples - https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
